"""Word report generator."""

import io
from datetime import datetime
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

from lexguard.models.contract import Contract
from lexguard.models.clause import ClauseType


def generate_docx_report(contract: Contract, risk_data: dict) -> bytes:
    """
    Generate a Word report for the contract analysis.

    Args:
        contract: Contract object
        risk_data: Risk assessment data

    Returns:
        bytes: Word file content
    """
    doc = Document()

    # Title
    title = doc.add_heading('LexGuard Contract Analysis', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Contract Info
    doc.add_heading('Contract Details', level=1)
    p = doc.add_paragraph()
    p.add_run('Filename: ').bold = True
    p.add_run(f"{contract.original_filename}\n")
    p.add_run('Analysis Date: ').bold = True
    p.add_run(f"{datetime.now().strftime('%Y-%m-%d %H:%M')}\n")
    p.add_run('Total Clauses: ').bold = True
    p.add_run(f"{len(contract.clauses)}")

    # Executive Summary
    doc.add_heading('Executive Summary', level=1)
    
    # Risk Overview
    doc.add_heading('Risk Assessment', level=2)
    
    high_risk = risk_data.get('high_risk_count', 0)
    medium_risk = risk_data.get('medium_risk_count', 0)
    low_risk = risk_data.get('low_risk_count', 0)
    
    p = doc.add_paragraph()
    p.add_run(f"High Risk Issues: {high_risk}").font.color.rgb = RGBColor(220, 53, 69)
    p.add_run('\n')
    p.add_run(f"Medium Risk Issues: {medium_risk}").font.color.rgb = RGBColor(255, 193, 7)
    p.add_run('\n')
    p.add_run(f"Low Risk Issues: {low_risk}").font.color.rgb = RGBColor(40, 167, 69)

    # Detailed Analysis
    doc.add_heading('Detailed Clause Analysis', level=1)

    # Sort clauses by risk (High -> Low)
    sorted_clauses = sorted(
        contract.clauses, 
        key=lambda x: x.risk_score if x.risk_score is not None else 0, 
        reverse=True
    )

    for i, clause in enumerate(sorted_clauses, 1):
        risk_level = clause.risk_level.upper() if clause.risk_level else "UNKNOWN"
        clause_type = clause.clause_type.replace('_', ' ').title()
        
        h = doc.add_heading(f"{i}. {clause_type}", level=2)
        
        # Add risk badge-like text
        p = doc.add_paragraph()
        run = p.add_run(f"RISK LEVEL: {risk_level}")
        run.bold = True
        
        if risk_level == 'HIGH':
            run.font.color.rgb = RGBColor(220, 53, 69)
        elif risk_level == 'MEDIUM':
            run.font.color.rgb = RGBColor(255, 193, 7)
        else:
            run.font.color.rgb = RGBColor(40, 167, 69)
            
        p.add_run(f" (Score: {clause.risk_score:.2f})")

        # Clause Text
        doc.add_heading('Clause Text:', level=3)
        p = doc.add_paragraph(clause.text)
        p.style = 'Quote'

    # Footer
    section = doc.sections[0]
    footer = section.footer
    p = footer.paragraphs[0]
    p.text = "Generated by LexGuard AI - Confidential"
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Save to bytes
    file_stream = io.BytesIO()
    doc.save(file_stream)
    file_stream.seek(0)
    return file_stream.getvalue()
